    /// <summary>
    /// Use auto-layout?
    /// </summary>
    public bool DoAutoLayout { get; set; } = true;



     // Identify all groups to keep/ungroup
      if (UngroupAll)
      {
        // Make sure that no groups are currently selected
        GeneralUtils.ClearSelection();


      // Process nodes before we call node to code
      // Make sure that no nodes are currently selected
      GeneralUtils.ClearSelection();



      // Auto layout
      if (DoAutoLayout)
      {
        // Make sure nothing is selected
        GeneralUtils.ClearSelection();
        // Here we'll need to call the auto-layout via Dynamo's Dispatcher
        // Otherwise the auto layout command will not yet be aware of the size 
        // of the code blocks generated by node to code and our graph will look less pretty.
        dynWindow.Dispatcher.BeginInvoke(DispatcherPriority.Background, new Action(() =>
        {
          viewModel.CurrentSpaceViewModel.GraphAutoLayoutCommand.Execute(null);
        }));
      }
